env:
  - PYTHONPATH=$PYTHONPATH:$(pwd)/mc_sim_fin CODECOV_TOKEN="148fc72c-8c86-468b-b5f4-e878fcc9ee93"
language: python
python:
  - "3.7"
install:
  - pip install -r requirements-dev.txt
jobs:
  include:
    - stage: test
      script:
        - pytest --cov=./ --flake8
        - codecov
        - python setup.py sdist
        - twine upload dist/mc-sim-fin-*.tar.gz -u gaugau3000 -p $PYPI_PASSWORD
